### ISSUE TITLE
redmine_wiki_html_util can not work on redmine 1.2.11

### ISSUE THREAD

**Issue by baicheng** [mexitek/redmine_wiki_html_util#1]
HI:
I install the redmine_wiki_html_util on redmine 1.2.11 . But it doesn't work . No any errors in the logs .

{{html(

<ul>
   <li>option 1</li>
   <li>option 2</li>
   <li>option 3</li>
</ul>

)}}

but shows 
- option 1
- option 2
- option 3

**Comment by mexitek** [comment]
I know that for now it works best if you have no whitespace in between your HTML tags.

Instead of:

<pre><code>
{{{html(
&lt;ul&gt;
&lt;li&gt;Option 1&lt;/li&gt;
&lt;li&gt;Option 2&lt;/li&gt;
&lt;/ul&gt;
)}}}
</code></pre>


Works best if like this:

```
{{{html(<ul><li>Option 1</li><li>Option 2</li></ul>)}}}
```

I am currently using this plugin at work with large blocks of HTML and it works fine.  I am currently working on improving the whitespace issue.

p.s. you can easily erase all whitespace between html tags with any text editor that supports regular expressions for find/replace.

Find: \t|\n
Replace with blank

**Comment by baicheng** [comment]
Hi Arlo Carreon:

<pre>
I copied strings "{{{html(&lt;ul&gt;&lt;li&gt;Option 1&lt;/li&gt;&lt;li&gt;Option 2&lt;/li&gt;&lt;/ul&gt;)}}}" 
to my wiki ,but it still doesn't work ! 

The wiki is :

{{{html(&lt;ul&gt;&lt;li&gt;Option 1&lt;/li&gt;&lt;li&gt;Option 2&lt;/li&gt;&lt;/ul&gt;)}}}

The result is:
{

```
Option 1
Option 2
```

}

I'm sure the plugin has installed ,i can see the information in  "Administration->Plugins"

THK

**Comment by mexitek** [comment]
baicheng,

I apologize for the above example, I do not know why I put 3 "{" and "}". In Redmine wikis you only use 2 "{" and "}" for macros.

I just spun up a new install of Redmine 1.2.1 and installed the plugin. The plugin works as expected. The HTML you pass to the html() macro will be **used** in the wiki content.

Doing:
`{{html(<ul><li>Option 1</li><li>Option 2</li></ul>)}}`

**WIll** show:
- Option 1
- Option 2

Maybe you were expecting a different output? If you wanted the HTML to show as plaintext then you do not need my plugin.  

To show HTML in plaintext you can use: 
`<pre><code class="html">
    <ul>
        <li>Option 1</li>
        <li>Option 2</li>
        <li>Option 3</li>
        <li>Option 4</li>
    </ul>
    </code></pre>`

Will show:

`````` <ul>
      <li>Option 1</li>
      <li>Option 2</li>
      <li>Option 3</li>
      <li>Option 4</li>
   </ul>```
``````
