### ISSUE TITLE
Not working - v2.3.1.stable

### ISSUE THREAD

**Issue by tvaughan73** [mexitek/redmine_wiki_html_util#8]
Not working for me anymore with latest redmine version.

Environment:
  Redmine version                          2.3.1.stable
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.13
  Environment                              production
  Database adapter                         Mysql2

**Comment by mexitek** [comment]
ok I will start looking into this. Thanks for the report.

**Comment by thimios** [comment]
Hi, the example is also not working for me on Redmine 2.3.3.stable.12240, see:

http://support.wantedpixel.com/projects/test/wiki

is there any chance to get a version compatible with Redmine 2.x ?

thanks a lot

**Comment by mexitek** [comment]
Yea a 2.x version is long over due. I don't use Redmine anymore but I can
look at it sometime next week.

If you figure out a fix, feel free to submit a pull request.

On Tuesday, October 29, 2013, Thimios wrote:

> Hi, the example is also not working for me on Redmine 2.3.3.stable.12240,
> see:
> 
> http://support.wantedpixel.com/projects/test/wiki
> 
> is there any chance to get a version compatible with Redmine 2.x ?
> 
> thanks a lot
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mexitek/redmine_wiki_html_util/issues/8#issuecomment-27330401
> .

## 

Arlo Carreon http://arlocarreon.com
Web Developer

**Comment by Thanatermesis** [comment]
2.4.1 here, not working too

**Comment by jchristophe** [comment]
Hi mexitek,

Thought you had made my day there but from what I understand you're not using redmine anymore and the plugin isn't "actively" maintained?

It's shame because it is an extremely neat set of macros you're providing us with. I've installed it with no issue but macros seem broken.

css() - never managed to get it to work
html() - works partially when code is written on 1 line
css_url() - not tested yet
js_url() - not tested yet

Environment:
  Redmine version                2.4.2.stable.12473
  Ruby version                      2.2.0-p-1 (2013-12-31) [x86_64-linux]
  Rails version                      3.2.16
  Environment                       production
  Database adapter              PostgreSQL

SCM:
  Subversion                        1.6.17
  Git                                     1.7.10.4          

Redmine plugins:
  event_notifications            1.0.0
  redmine_ckeditor              1.0.15
  redmine_custom_css         0.1.2
  redmine_gist                      0.0.1

I'm not a coder so I probably won't be able to help there but I can provide you with a testing platform if you're interested in perusing dev.

Best,
JS

**Comment by mexitek** [comment]
That sounds great. Setup an env for me and email me the creds. I'll spend
some time this week to get a working version for 2.4.

arlo.carreon@gmail.com

On Tuesday, February 25, 2014, jchristophe notifications@github.com wrote:

> Hi mexitek,
> 
> Thought you had made my day there but from what I understand you're not
> using redmine anymore and the plugin isn't "actively" maintained?
> 
> It's shame because it is an extremely neat set of macros you're providing
> us with. I've installed it with no issue but macros seem broken.
> 
> css() - never managed to get it to work
> html() - works partially when code is written on 1 line
> css_url() - not tested yet
> js_url() - not tested yet
> 
> Environment:
> Redmine version 2.4.2.stable.12473
> Ruby version 2.2.0-p-1 (2013-12-31) [x86_64-linux]
> Rails version 3.2.16
> Environment production
> Database adapter PostgreSQL
> 
> SCM:
> Subversion 1.6.17
> Git 1.7.10.4
> 
> Redmine plugins:
> event_notifications 1.0.0
> redmine_ckeditor 1.0.15
> redmine_custom_css 0.1.2
> redmine_gist 0.0.1
> 
> I'm not a coder so I probably won't be able to help there but I can
> provide you with a testing platform if you're interested in perusing dev.
> 
> Best,
> JS
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/mexitek/redmine_wiki_html_util/issues/8#issuecomment-36031509
> .

## 

Arlo Carreon http://arlocarreon.com
Web Developer

**Comment by jchristophe** [comment]
Hey Arlo,
Not sure you got my mail but env is ready. My email is jchristophe@inmtxx.me
JS

**Comment by mexitek** [comment]
Awesome! I'll reply there.

On Thursday, February 27, 2014, jchristophe notifications@github.com
wrote:

> Hey Arlo,
> Not sure you got my mail but env is ready. My email is
> jchristophe@inmtxx.me<javascript:_e(%7B%7D,'cvml','jchristophe@inmtxx.me');>
> JS
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/mexitek/redmine_wiki_html_util/issues/8#issuecomment-36257576
> .

## 

Arlo Carreon http://arlocarreon.com
Web Developer

**Comment by mexitek** [comment]
Got it working thanks to @jchristophe testing environment. Should now work with any version 2.1+. Redmine made changes to macro definitions in 2.1. I hope they work for all now.

All changes are in master branch.

**Comment by jchristophe** [comment]
Great stuff thanks. Will test extensively and get back to you if I find any issues.
PS: Sent you an email too... ;p
